/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg5_ricardogonzalez_11651018;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class Power_Squad extends javax.swing.JFrame {

    ArrayList Nombres = new ArrayList();
    ArrayList<Hero> Heroes = new ArrayList();
    ArrayList<Villano> Villanos = new ArrayList();
    ArrayList HeroSquad = new ArrayList();
    ArrayList VillainSquad = new ArrayList();

    public Power_Squad() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Character = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Squads = new javax.swing.JList<>();
        characterpoder = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        TitleCreateSquad2 = new javax.swing.JLabel();
        characterdebilidad = new javax.swing.JTextField();
        characternombre = new javax.swing.JTextField();
        CrearChara = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Squad = new javax.swing.JDialog();
        SquadCreate = new javax.swing.JPanel();
        squadlocal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TitleCreateSquad = new javax.swing.JLabel();
        Hero = new javax.swing.JRadioButton();
        Villano = new javax.swing.JRadioButton();
        squadphrase = new javax.swing.JTextField();
        squadnombre = new javax.swing.JTextField();
        Crear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        squadlocal1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TitleCreateSquad1 = new javax.swing.JLabel();
        Hero1 = new javax.swing.JRadioButton();
        Villano1 = new javax.swing.JRadioButton();
        squadphrase1 = new javax.swing.JTextField();
        squadnombre1 = new javax.swing.JTextField();
        Crear1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Crearimage = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Squads.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(Squads);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 200, -1));

        characterpoder.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(characterpoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 330, 30));

        jLabel15.setFont(new java.awt.Font("RWBY_Style", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Name");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel16.setFont(new java.awt.Font("RWBY_Style", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Power");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 30));

        jLabel17.setFont(new java.awt.Font("RWBY_Style", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Weakness");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        TitleCreateSquad2.setFont(new java.awt.Font("RWBY_Style", 3, 36)); // NOI18N
        TitleCreateSquad2.setForeground(new java.awt.Color(0, 0, 255));
        TitleCreateSquad2.setText("Create character");
        jPanel2.add(TitleCreateSquad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 300, -1));

        characterdebilidad.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(characterdebilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 330, 30));

        characternombre.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(characternombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 330, 30));

        CrearChara.setFont(new java.awt.Font("RWBY_Style", 3, 36)); // NOI18N
        CrearChara.setText("Create");
        CrearChara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearCharaMouseClicked(evt);
            }
        });
        jPanel2.add(CrearChara, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 140, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/pkg5_ricardogonzalez_11651018/New-Angel-Wings-8944.jpg"))); // NOI18N
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout CharacterLayout = new javax.swing.GroupLayout(Character.getContentPane());
        Character.getContentPane().setLayout(CharacterLayout);
        CharacterLayout.setHorizontalGroup(
            CharacterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CharacterLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        CharacterLayout.setVerticalGroup(
            CharacterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        SquadCreate.setPreferredSize(new java.awt.Dimension(500, 500));
        SquadCreate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        squadlocal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        SquadCreate.add(squadlocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 330, 30));

        jLabel8.setFont(new java.awt.Font("RWBY_Style", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Name");
        SquadCreate.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel9.setFont(new java.awt.Font("RWBY_Style", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Base Location");
        SquadCreate.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 30));

        jLabel10.setFont(new java.awt.Font("RWBY_Style", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Phrase");
        SquadCreate.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        TitleCreateSquad.setFont(new java.awt.Font("RWBY_Style", 3, 36)); // NOI18N
        TitleCreateSquad.setForeground(new java.awt.Color(255, 0, 0));
        TitleCreateSquad.setText("Create Squad");
        SquadCreate.add(TitleCreateSquad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 220, -1));

        Hero.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Hero);
        Hero.setFont(new java.awt.Font("RWBY_Style", 0, 24)); // NOI18N
        Hero.setText("Hero");
        SquadCreate.add(Hero, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        Villano.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(Villano);
        Villano.setFont(new java.awt.Font("RWBY_Style", 0, 24)); // NOI18N
        Villano.setForeground(new java.awt.Color(255, 255, 255));
        Villano.setText("Villain");
        SquadCreate.add(Villano, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));

        squadphrase.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        SquadCreate.add(squadphrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 330, 30));

        squadnombre.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        SquadCreate.add(squadnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 330, 30));

        Crear.setFont(new java.awt.Font("RWBY_Style", 3, 36)); // NOI18N
        Crear.setText("Create");
        Crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearMouseClicked(evt);
            }
        });
        SquadCreate.add(Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 140, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/pkg5_ricardogonzalez_11651018/New-Angel-Wings-8944.jpg"))); // NOI18N
        SquadCreate.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout SquadLayout = new javax.swing.GroupLayout(Squad.getContentPane());
        Squad.getContentPane().setLayout(SquadLayout);
        SquadLayout.setHorizontalGroup(
            SquadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(SquadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SquadLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(SquadCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        SquadLayout.setVerticalGroup(
            SquadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(SquadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SquadLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(SquadCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        squadlocal1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("RWBY_Style", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Name");

        jLabel12.setFont(new java.awt.Font("RWBY_Style", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Base Location");

        jLabel13.setFont(new java.awt.Font("RWBY_Style", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Phrase");

        TitleCreateSquad1.setFont(new java.awt.Font("RWBY_Style", 3, 36)); // NOI18N
        TitleCreateSquad1.setForeground(new java.awt.Color(255, 0, 0));
        TitleCreateSquad1.setText("Create Squad");

        Hero1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(Hero1);
        Hero1.setFont(new java.awt.Font("RWBY_Style", 0, 24)); // NOI18N
        Hero1.setText("Hero");

        Villano1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(Villano1);
        Villano1.setFont(new java.awt.Font("RWBY_Style", 0, 24)); // NOI18N
        Villano1.setForeground(new java.awt.Color(255, 255, 255));
        Villano1.setText("Villain");

        squadphrase1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        squadnombre1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        Crear1.setFont(new java.awt.Font("RWBY_Style", 3, 36)); // NOI18N
        Crear1.setText("Create");
        Crear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Crear1MouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/pkg5_ricardogonzalez_11651018/New-Angel-Wings-8944.jpg"))); // NOI18N

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(750, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("JLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        Crearimage.setText("jLabel1");
        Crearimage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearimageMouseClicked(evt);
            }
        });
        jPanel1.add(Crearimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        jLabel3.setText("jLabel1");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        jLabel4.setText("jLabel1");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, -1, -1));

        Title.setFont(new java.awt.Font("RWBY_Style", 3, 36)); // NOI18N
        Title.setText("Power Squad");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 220, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearMouseClicked
        String nombre;
        String localidad;
        String frase;
        String lider;
        String tipo;
        try {
            nombre = squadnombre.getText();
            localidad = squadlocal.getText();
            frase = squadphrase.getText();
            if (Nombres.contains(nombre)) {
                JOptionPane.showMessageDialog(Squad, "Este nombre ya existe.", "ERROR", JOptionPane.ERROR_MESSAGE);
                nombre = "";
            } else {
                lider = "Sin Lider";
                if (Hero.isSelected()) {
                    tipo = "Hero";
                } else {
                    tipo = "Villain";
                }
                if (tipo.equals("Hero")) {
                    Nombres.add(nombre);
                    HeroSquad.add(new Squad(nombre, localidad, frase, lider, tipo));
                    JOptionPane.showMessageDialog(Squad, "Escaudron guardado!");
                    Hero.setSelected(false);
                } else if (tipo.equals("Villain")) {
                    Nombres.add(nombre);
                    VillainSquad.add(new Squad(nombre, localidad, frase, lider, tipo));
                    JOptionPane.showMessageDialog(Squad, "Escuadron guardado!");
                    Villano.setSelected(false);
                }
            }
        } catch (Exception x) {
            JOptionPane.showMessageDialog(Squad, "Revise sus datos ingresados.", "ERROR", JOptionPane.ERROR_MESSAGE);
            x.printStackTrace();
        }
        squadnombre.setText("");
        squadlocal.setText("");
        squadphrase.setText("");
        nombre = "";
        localidad = "";
        frase = "";
        lider = "";
        tipo = "";
        
    }//GEN-LAST:event_CrearMouseClicked

    private void CrearimageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearimageMouseClicked
        Squad.setModal(true);
        Squad.pack();
        Squad.setLocationRelativeTo(this);
        Squad.setVisible(true);
    }//GEN-LAST:event_CrearimageMouseClicked

    private void Crear1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Crear1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Crear1MouseClicked

    private void CrearCharaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearCharaMouseClicked
//        String nombre;
//        String poder;
//        String debilidad;
//        String escuadron;
//        int fuerza;
//        int agilidad;
//        int mental;
//        
//        try {
//            nombre = squadnombre.getText();
//            poder = squadlocal.getText();
//            debilidad = squadphrase.getText();
//            escuadron = "";
//            if (Nombres.contains(nombre)) {
//                JOptionPane.showMessageDialog(Squad, "Estenombre ya existe.", "ERROR", JOptionPane.ERROR_MESSAGE);
//                nombre = "";
//            } else {
//                
//                if (Hero.isSelected()) {
//                    tipo = "Hero";
//                } else {
//                    tipo = "Villain";
//                }
//                if (tipo.equals("Hero")) {
//                    Nombres.add(nombre);
//                    HeroSquad.add(new Squad(nombre, localidad, frase, lider, tipo));
//                    JOptionPane.showMessageDialog(Squad, "Heroe guardado!");
//                    Hero.setSelected(false);
//                } else if (tipo.equals("Villain")) {
//                    Nombres.add(nombre);
//                    VillainSquad.add(new Squad(nombre, localidad, frase, lider, tipo));
//                    JOptionPane.showMessageDialog(Squad, "Villano guardado!");
//                    Villano.setSelected(false);
//                }
//            }
//        } catch (Exception x) {
//            JOptionPane.showMessageDialog(Squad, "Revise sus datos ingresados.", "ERROR", JOptionPane.ERROR_MESSAGE);
//            x.printStackTrace();
//        }
//        squadnombre.setText("");
//        squadlocal.setText("");
//        squadphrase.setText("");
//        nombre = "";
//        localidad = "";
//        frase = "";
//        lider = "";
//        tipo = "";
    }//GEN-LAST:event_CrearCharaMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Character.setModal(true);
        Character.pack();
        Character.setLocationRelativeTo(this);
        Character.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Power_Squad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Power_Squad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Power_Squad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Power_Squad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Power_Squad().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Character;
    private javax.swing.JButton Crear;
    private javax.swing.JButton Crear1;
    private javax.swing.JButton CrearChara;
    private javax.swing.JLabel Crearimage;
    private javax.swing.JRadioButton Hero;
    private javax.swing.JRadioButton Hero1;
    private javax.swing.JDialog Squad;
    private javax.swing.JPanel SquadCreate;
    private javax.swing.JList<String> Squads;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel TitleCreateSquad;
    private javax.swing.JLabel TitleCreateSquad1;
    private javax.swing.JLabel TitleCreateSquad2;
    private javax.swing.JRadioButton Villano;
    private javax.swing.JRadioButton Villano1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField characterdebilidad;
    private javax.swing.JTextField characternombre;
    private javax.swing.JTextField characterpoder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField squadlocal;
    private javax.swing.JTextField squadlocal1;
    private javax.swing.JTextField squadnombre;
    private javax.swing.JTextField squadnombre1;
    private javax.swing.JTextField squadphrase;
    private javax.swing.JTextField squadphrase1;
    // End of variables declaration//GEN-END:variables
}
